- name: Create First Linode
  hosts: localhost
  vars_files:
      - ./group_vars/k3s_group/vars
  tasks:

  - name: Create three linode serves for k3s HA clustering.
    linode_v4:
      label: "{{ label }}{{ item }}"
      access_token: "{{ token }}"
      type: g6-nanode-1
      region: us-west
      image: linode/ubuntu18.04
      root_pass: "{{ password }}"
      authorized_keys: "{{ ssh_keys }}"
      group: k3s_group
      tags: k3s_group
      state: present
    loop:
      - "01"
      - "02"
      - "03"
    register: k3s_servers

  - name: "Build hosts file"
    become: true
    lineinfile:
      path: /etc/hosts
      regexp: '.*{{ item.instance.label }}$'
      line: '{{item.instance.ipv4[0]}} {{item.instance.label}}'
      state: present
    with_items: "{{k3s_servers.results}}"